
# Mapping from excel file column name to db column name
column_name_mapping = {
    'Type Ligne': 'type_ligne',
    'Identifiant de l\'élément': 'identifiant_element',
    'Structure': 'structure',
    'Statut de l\'élément': 'statut_element',
    'Nom base français': 'nom_base_francais',
    'Nom attribut français': 'nom_attribut_francais',
    'Nom frontière français': 'nom_frontiere_francais',
    'Code de la catégorie': 'code_categorie',
    'Tags français': 'tags_francais',
    'Unité français': 'unite_francais',
    'Contributeur': 'contributeur',
    'Programme': 'programme',
    'Url du programme': 'url_programme',
    'Source': 'source',
    'Localisation géographique': 'localisation_geographique',
    'Sous-localisation géographique français': 'sous_localisation_geographique_francais',
    'Date de création': 'date_creation',
    'Date de modification': 'date_modification',
    'Période de validité': 'periode_validite',
    'Incertitude': 'incertitude',
    'Réglementations': 'regulations',
    'Transparence': 'transparence',
    'Qualité': 'qualite',
    'Qualité TeR': 'qualite_ter',
    'Qualité GR': 'qualite_gr',
    'Qualité TiR': 'qualite_tir',
    'Qualité C': 'qualite_c',
    'Qualité P': 'qualite_p',
    'Qualité M': 'qualite_m',
    'Commentaire français': 'commentaire_francais',
    'Type poste': 'type_poste',
    'Nom poste français': 'nom_poste_francais',
    'Total poste non décomposé': 'total_poste_non_decompose',
    'CO2f': 'co2f',
    'CH4f': 'ch4f',
    'CH4b': 'ch4b',
    'N2O': 'n2o',
    'Code gaz supplémentaire 1': 'code_gaz_sup_1',
    'Valeur gaz supplémentaire 1': 'valeur_gaz_sup_1',
    'Code gaz supplémentaire 2': 'code_gaz_sup_2',
    'Valeur gaz supplémentaire 2': 'valeur_gaz_sup_2',
    'Code gaz supplémentaire 3': 'code_gaz_sup_3',
    'Valeur gaz supplémentaire 3': 'valeur_gaz_sup_3',
    'Code gaz supplémentaire 4': 'code_gaz_sup_4',
    'Valeur gaz supplémentaire 4': 'valeur_gaz_sup_4',
    'Code gaz supplémentaire 5': 'code_gaz_sup_5',
    'Valeur gaz supplémentaire 5': 'valeur_gaz_sup_5',
    'Autres GES': 'autres_ges',
    'CO2b': 'co2b'
    }